### ISSUE TITLE
PRINT $FD00 just says Unknown Variable

### ISSUE THREAD

**Issue by shifters67** [dp111/Pi1MHz#6]
Latest build (02062011 beta) of software.  When booting (and pressing CTRL-BREAK after 10 seconds to ensure its up) - if you then enter 'PRINT $FD00' at the command line as indicated in the git readme - it just comes back as 'unknown variable'

**Comment by hoglet67** [comment]
That's a typo in the README.

Try:
```
PRINT $&FD00
```

**Comment by dp111** [comment]
Latest beta here [https://stardot.org.uk/forums/viewtopic.php?f=3&t=19513&p=366874#p366874](url)

**Comment by dp111** [comment]
Fixed
