### ISSUE TITLE
JIM RAM paging registers offset by one

### ISSUE THREAD

**Issue by hoglet67** [dp111/Pi1MHz#7]
See discussion here:
https://stardot.org.uk/forums/viewtopic.php?p=440527#p440527

Fix I think is to get rid of the extra offset on these three lines:
https://github.com/dp111/Pi1MHz/blob/4f777fc3049deb72984c2432e65b206e63219e32/src/ram_emulator.c#L131-L133

Introduced in 53733e3e, so it's been in all releases after v1.13

Work around is to put the following in cmdline.txt:
```
Rampage_addr=0xfc
```

Dave

**Comment by dp111** [comment]
Thanks for finding this, fixed in commit 5a57029
